name = "Cup"
license = "MIT"
licenselink = "https://github.com/kmuncie/hugo-cup-theme/blob/master/LICENSE"
description = "An accessibility-friendly Hugo blog theme, adapted from the adapted Cupper theme."
homepage = "https://github.com/kmuncie/hugo-cup-theme"
tags = ["accessible", "blog", "minimal"]
features = ["accessible", "blog", "minimal"]
min_version = "0.58.3"

[author]
  name = "Kevin Muncie"
  homepage = "https://kmuncie.com"

[original]
  name = "Cupper"
  homepage = "https://thepaciellogroup.github.io/cupper/"
  repo = "https://github.com/ThePacielloGroup/cupper"
